//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.28 at 04:15:23 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://country.domain.webservice.sample.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.sample.webservice.domain.country;
