info:
 description: Sample Application
 version: 
endpoints:
 restart:
  enabled: true
 shutdown:
  enabled: true
 health:
  enabled: true
  sensitive: false

---
dataSource:
 dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
 driverClassName: com.mysql.jdbc.Driver
 jdbcUrl: jdbc:mysql://localhost:3306/chinook?&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
 username: root
 password: root
 maximumPoolSize: 5
 maxLifetimeMs: 30000
 idleTimeoutMs: 30000
 poolName: HIKARI-POOL
hibernate.dialect: MySQL5
hibernate.show_sql: false
hibernate.format_sql: true

