CREATE TABLE COUNTRY (
  id INTEGER(11) PRIMARY KEY,
  iso VARCHAR(2),
  name VARCHAR(80),
  meta_data_1 VARCHAR(80),
  meta_data_2 VARCHAR(80),
  meta_data_3 VARCHAR(80),
  meta_data_4 VARCHAR(80)
);

INSERT INTO COUNTRY VALUES(1, 'AF', 'Afganistán',null,null,null,null);
INSERT INTO COUNTRY VALUES(2, 'AX', 'Islas Gland',null,null,null,null);
INSERT INTO COUNTRY VALUES(3, 'AL', 'Albania',null,null,null,null);
INSERT INTO COUNTRY VALUES(4, 'DE', 'Alemania',null,null,null,null);
INSERT INTO COUNTRY VALUES(5, 'AD', 'Andorra',null,null,null,null);
INSERT INTO COUNTRY VALUES(6, 'AO', 'Angola',null,null,null,null);
INSERT INTO COUNTRY VALUES(7, 'AI', 'Anguilla',null,null,null,null);
INSERT INTO COUNTRY VALUES(8, 'AQ', 'Antártida',null,null,null,null);
INSERT INTO COUNTRY VALUES(9, 'AG', 'Antigua y Barbuda',null,null,null,null);
INSERT INTO COUNTRY VALUES(10, 'AN', 'Antillas Holandesas',null,null,null,null);
INSERT INTO COUNTRY VALUES(11, 'SA', 'Arabia Saudí',null,null,null,null);
INSERT INTO COUNTRY VALUES(12, 'DZ', 'Argelia',null,null,null,null);
INSERT INTO COUNTRY VALUES(13, 'AR', 'Argentina',null,null,null,null);
INSERT INTO COUNTRY VALUES(14, 'AM', 'Armenia',null,null,null,null);
INSERT INTO COUNTRY VALUES(15, 'AW', 'Aruba',null,null,null,null);
INSERT INTO COUNTRY VALUES(16, 'AU', 'Australia',null,null,null,null);
INSERT INTO COUNTRY VALUES(17, 'AT', 'Austria',null,null,null,null);
INSERT INTO COUNTRY VALUES(18, 'AZ', 'Azerbaiyán',null,null,null,null);
INSERT INTO COUNTRY VALUES(19, 'BS', 'Bahamas',null,null,null,null);
INSERT INTO COUNTRY VALUES(20, 'BH', 'Bahréin',null,null,null,null);
INSERT INTO COUNTRY VALUES(21, 'BD', 'Bangladesh',null,null,null,null);
INSERT INTO COUNTRY VALUES(22, 'BB', 'Barbados',null,null,null,null);
INSERT INTO COUNTRY VALUES(23, 'BY', 'Bielorrusia',null,null,null,null);
INSERT INTO COUNTRY VALUES(24, 'BE', 'Bélgica',null,null,null,null);
INSERT INTO COUNTRY VALUES(25, 'BZ', 'Belice',null,null,null,null);
INSERT INTO COUNTRY VALUES(26, 'BJ', 'Benin',null,null,null,null);
INSERT INTO COUNTRY VALUES(27, 'BM', 'Bermudas',null,null,null,null);
INSERT INTO COUNTRY VALUES(28, 'BT', 'Bhután',null,null,null,null);
INSERT INTO COUNTRY VALUES(29, 'BO', 'Bolivia',null,null,null,null);
INSERT INTO COUNTRY VALUES(30, 'BA', 'Bosnia y Herzegovina',null,null,null,null);
INSERT INTO COUNTRY VALUES(31, 'BW', 'Botsuana',null,null,null,null);
INSERT INTO COUNTRY VALUES(32, 'BV', 'Isla Bouvet',null,null,null,null);
INSERT INTO COUNTRY VALUES(33, 'BR', 'Brasil',null,null,null,null);
INSERT INTO COUNTRY VALUES(34, 'BN', 'Brunéi',null,null,null,null);
INSERT INTO COUNTRY VALUES(35, 'BG', 'Bulgaria',null,null,null,null);
INSERT INTO COUNTRY VALUES(36, 'BF', 'Burkina Faso',null,null,null,null);
INSERT INTO COUNTRY VALUES(37, 'BI', 'Burundi',null,null,null,null);
INSERT INTO COUNTRY VALUES(38, 'CV', 'Cabo Verde',null,null,null,null);
INSERT INTO COUNTRY VALUES(39, 'KY', 'Islas Caimán',null,null,null,null);
INSERT INTO COUNTRY VALUES(40, 'KH', 'Camboya',null,null,null,null);
INSERT INTO COUNTRY VALUES(41, 'CM', 'Camerún',null,null,null,null);
INSERT INTO COUNTRY VALUES(42, 'CA', 'Canadá',null,null,null,null);
INSERT INTO COUNTRY VALUES(43, 'CF', 'República Centroafricana',null,null,null,null);
INSERT INTO COUNTRY VALUES(44, 'TD', 'Chad',null,null,null,null);
INSERT INTO COUNTRY VALUES(45, 'CZ', 'República Checa',null,null,null,null);
INSERT INTO COUNTRY VALUES(46, 'CL', 'Chile',null,null,null,null);
INSERT INTO COUNTRY VALUES(47, 'CN', 'China',null,null,null,null);
INSERT INTO COUNTRY VALUES(48, 'CY', 'Chipre',null,null,null,null);
INSERT INTO COUNTRY VALUES(49, 'CX', 'Isla de Navidad',null,null,null,null);
INSERT INTO COUNTRY VALUES(50, 'VA', 'Ciudad del Vaticano',null,null,null,null);
INSERT INTO COUNTRY VALUES(51, 'CC', 'Islas Cocos',null,null,null,null);
INSERT INTO COUNTRY VALUES(52, 'CO', 'Colombia',null,null,null,null);
INSERT INTO COUNTRY VALUES(53, 'KM', 'Comoras',null,null,null,null);
INSERT INTO COUNTRY VALUES(54, 'CD', 'República Democrática del Congo',null,null,null,null);
INSERT INTO COUNTRY VALUES(55, 'CG', 'Congo',null,null,null,null);
INSERT INTO COUNTRY VALUES(56, 'CK', 'Islas Cook',null,null,null,null);
INSERT INTO COUNTRY VALUES(57, 'KP', 'Corea del Norte',null,null,null,null);
INSERT INTO COUNTRY VALUES(58, 'KR', 'Corea del Sur',null,null,null,null);
INSERT INTO COUNTRY VALUES(59, 'CI', 'Costa de Marfil',null,null,null,null);
INSERT INTO COUNTRY VALUES(60, 'CR', 'Costa Rica',null,null,null,null);
INSERT INTO COUNTRY VALUES(61, 'HR', 'Croacia',null,null,null,null);
INSERT INTO COUNTRY VALUES(62, 'CU', 'Cuba',null,null,null,null);
INSERT INTO COUNTRY VALUES(63, 'DK', 'Dinamarca',null,null,null,null);
INSERT INTO COUNTRY VALUES(64, 'DM', 'Dominica',null,null,null,null);
INSERT INTO COUNTRY VALUES(65, 'DO', 'República Dominicana',null,null,null,null);
INSERT INTO COUNTRY VALUES(66, 'EC', 'Ecuador',null,null,null,null);
INSERT INTO COUNTRY VALUES(67, 'EG', 'Egipto',null,null,null,null);
INSERT INTO COUNTRY VALUES(68, 'SV', 'El Salvador',null,null,null,null);
INSERT INTO COUNTRY VALUES(69, 'AE', 'Emiratos Árabes Unidos',null,null,null,null);
INSERT INTO COUNTRY VALUES(70, 'ER', 'Eritrea',null,null,null,null);
INSERT INTO COUNTRY VALUES(71, 'SK', 'Eslovaquia',null,null,null,null);
INSERT INTO COUNTRY VALUES(72, 'SI', 'Eslovenia',null,null,null,null);
INSERT INTO COUNTRY VALUES(73, 'ES', 'España',null,null,null,null);
INSERT INTO COUNTRY VALUES(74, 'UM', 'Islas ultramarinas de Estados Unidos',null,null,null,null);
INSERT INTO COUNTRY VALUES(75, 'US', 'Estados Unidos',null,null,null,null);
INSERT INTO COUNTRY VALUES(76, 'EE', 'Estonia',null,null,null,null);
INSERT INTO COUNTRY VALUES(77, 'ET', 'Etiopía',null,null,null,null);
INSERT INTO COUNTRY VALUES(78, 'FO', 'Islas Feroe',null,null,null,null);
INSERT INTO COUNTRY VALUES(79, 'PH', 'Filipinas',null,null,null,null);
INSERT INTO COUNTRY VALUES(80, 'FI', 'Finlandia',null,null,null,null);
INSERT INTO COUNTRY VALUES(81, 'FJ', 'Fiyi',null,null,null,null);
INSERT INTO COUNTRY VALUES(82, 'FR', 'Francia',null,null,null,null);
INSERT INTO COUNTRY VALUES(83, 'GA', 'Gabón',null,null,null,null);
INSERT INTO COUNTRY VALUES(84, 'GM', 'Gambia',null,null,null,null);
INSERT INTO COUNTRY VALUES(85, 'GE', 'Georgia',null,null,null,null);
INSERT INTO COUNTRY VALUES(86, 'GS', 'Islas Georgias del Sur y Sandwich del Sur',null,null,null,null);
INSERT INTO COUNTRY VALUES(87, 'GH', 'Ghana',null,null,null,null);
INSERT INTO COUNTRY VALUES(88, 'GI', 'Gibraltar',null,null,null,null);
INSERT INTO COUNTRY VALUES(89, 'GD', 'Granada',null,null,null,null);
INSERT INTO COUNTRY VALUES(90, 'GR', 'Grecia',null,null,null,null);
INSERT INTO COUNTRY VALUES(91, 'GL', 'Groenlandia',null,null,null,null);
INSERT INTO COUNTRY VALUES(92, 'GP', 'Guadalupe',null,null,null,null);
INSERT INTO COUNTRY VALUES(93, 'GU', 'Guam',null,null,null,null);
INSERT INTO COUNTRY VALUES(94, 'GT', 'Guatemala',null,null,null,null);
INSERT INTO COUNTRY VALUES(95, 'GF', 'Guayana Francesa',null,null,null,null);
INSERT INTO COUNTRY VALUES(96, 'GN', 'Guinea',null,null,null,null);
INSERT INTO COUNTRY VALUES(97, 'GQ', 'Guinea Ecuatorial',null,null,null,null);
INSERT INTO COUNTRY VALUES(98, 'GW', 'Guinea-Bissau',null,null,null,null);
INSERT INTO COUNTRY VALUES(99, 'GY', 'Guyana',null,null,null,null);
INSERT INTO COUNTRY VALUES(100, 'HT', 'Haití',null,null,null,null);
INSERT INTO COUNTRY VALUES(101, 'HM', 'Islas Heard y McDonald',null,null,null,null);
INSERT INTO COUNTRY VALUES(102, 'HN', 'Honduras',null,null,null,null);
INSERT INTO COUNTRY VALUES(103, 'HK', 'Hong Kong',null,null,null,null);
INSERT INTO COUNTRY VALUES(104, 'HU', 'Hungría',null,null,null,null);
INSERT INTO COUNTRY VALUES(105, 'IN', 'India',null,null,null,null);
INSERT INTO COUNTRY VALUES(106, 'ID', 'Indonesia',null,null,null,null);
INSERT INTO COUNTRY VALUES(107, 'IR', 'Irán',null,null,null,null);
INSERT INTO COUNTRY VALUES(108, 'IQ', 'Iraq',null,null,null,null);
INSERT INTO COUNTRY VALUES(109, 'IE', 'Irlanda',null,null,null,null);
INSERT INTO COUNTRY VALUES(110, 'IS', 'Islandia',null,null,null,null);
INSERT INTO COUNTRY VALUES(111, 'IL', 'Israel',null,null,null,null);
INSERT INTO COUNTRY VALUES(112, 'IT', 'Italia',null,null,null,null);
INSERT INTO COUNTRY VALUES(113, 'JM', 'Jamaica',null,null,null,null);
INSERT INTO COUNTRY VALUES(114, 'JP', 'Japón',null,null,null,null);
INSERT INTO COUNTRY VALUES(115, 'JO', 'Jordania',null,null,null,null);
INSERT INTO COUNTRY VALUES(116, 'KZ', 'Kazajstán',null,null,null,null);
INSERT INTO COUNTRY VALUES(117, 'KE', 'Kenia',null,null,null,null);
INSERT INTO COUNTRY VALUES(118, 'KG', 'Kirguistán',null,null,null,null);
INSERT INTO COUNTRY VALUES(119, 'KI', 'Kiribati',null,null,null,null);
INSERT INTO COUNTRY VALUES(120, 'KW', 'Kuwait',null,null,null,null);
INSERT INTO COUNTRY VALUES(121, 'LA', 'Laos',null,null,null,null);
INSERT INTO COUNTRY VALUES(122, 'LS', 'Lesotho',null,null,null,null);
INSERT INTO COUNTRY VALUES(123, 'LV', 'Letonia',null,null,null,null);
INSERT INTO COUNTRY VALUES(124, 'LB', 'Líbano',null,null,null,null);
INSERT INTO COUNTRY VALUES(125, 'LR', 'Liberia',null,null,null,null);
INSERT INTO COUNTRY VALUES(126, 'LY', 'Libia',null,null,null,null);
INSERT INTO COUNTRY VALUES(127, 'LI', 'Liechtenstein',null,null,null,null);
INSERT INTO COUNTRY VALUES(128, 'LT', 'Lituania',null,null,null,null);
INSERT INTO COUNTRY VALUES(129, 'LU', 'Luxemburgo',null,null,null,null);
INSERT INTO COUNTRY VALUES(130, 'MO', 'Macao',null,null,null,null);
INSERT INTO COUNTRY VALUES(131, 'MK', 'ARY Macedonia',null,null,null,null);
INSERT INTO COUNTRY VALUES(132, 'MG', 'Madagascar',null,null,null,null);
INSERT INTO COUNTRY VALUES(133, 'MY', 'Malasia',null,null,null,null);
INSERT INTO COUNTRY VALUES(134, 'MW', 'Malawi',null,null,null,null);
INSERT INTO COUNTRY VALUES(135, 'MV', 'Maldivas',null,null,null,null);
INSERT INTO COUNTRY VALUES(136, 'ML', 'Malí',null,null,null,null);
INSERT INTO COUNTRY VALUES(137, 'MT', 'Malta',null,null,null,null);
INSERT INTO COUNTRY VALUES(138, 'FK', 'Islas Malvinas',null,null,null,null);
INSERT INTO COUNTRY VALUES(139, 'MP', 'Islas Marianas del Norte',null,null,null,null);
INSERT INTO COUNTRY VALUES(140, 'MA', 'Marruecos',null,null,null,null);
INSERT INTO COUNTRY VALUES(141, 'MH', 'Islas Marshall',null,null,null,null);
INSERT INTO COUNTRY VALUES(142, 'MQ', 'Martinica',null,null,null,null);
INSERT INTO COUNTRY VALUES(143, 'MU', 'Mauricio',null,null,null,null);
INSERT INTO COUNTRY VALUES(144, 'MR', 'Mauritania',null,null,null,null);
INSERT INTO COUNTRY VALUES(145, 'YT', 'Mayotte',null,null,null,null);
INSERT INTO COUNTRY VALUES(146, 'MX', 'México',null,null,null,null);
INSERT INTO COUNTRY VALUES(147, 'FM', 'Micronesia',null,null,null,null);
INSERT INTO COUNTRY VALUES(148, 'MD', 'Moldavia',null,null,null,null);
INSERT INTO COUNTRY VALUES(149, 'MC', 'Mónaco',null,null,null,null);
INSERT INTO COUNTRY VALUES(150, 'MN', 'Mongolia',null,null,null,null);
INSERT INTO COUNTRY VALUES(151, 'MS', 'Montserrat',null,null,null,null);
INSERT INTO COUNTRY VALUES(152, 'MZ', 'Mozambique',null,null,null,null);
INSERT INTO COUNTRY VALUES(153, 'MM', 'Myanmar',null,null,null,null);
INSERT INTO COUNTRY VALUES(154, 'NA', 'Namibia',null,null,null,null);
INSERT INTO COUNTRY VALUES(155, 'NR', 'Nauru',null,null,null,null);
INSERT INTO COUNTRY VALUES(156, 'NP', 'Nepal',null,null,null,null);
INSERT INTO COUNTRY VALUES(157, 'NI', 'Nicaragua',null,null,null,null);
INSERT INTO COUNTRY VALUES(158, 'NE', 'Níger',null,null,null,null);
INSERT INTO COUNTRY VALUES(159, 'NG', 'Nigeria',null,null,null,null);
INSERT INTO COUNTRY VALUES(160, 'NU', 'Niue',null,null,null,null);
INSERT INTO COUNTRY VALUES(161, 'NF', 'Isla Norfolk',null,null,null,null);
INSERT INTO COUNTRY VALUES(162, 'NO', 'Noruega',null,null,null,null);
INSERT INTO COUNTRY VALUES(163, 'NC', 'Nueva Caledonia',null,null,null,null);
INSERT INTO COUNTRY VALUES(164, 'NZ', 'Nueva Zelanda',null,null,null,null);
INSERT INTO COUNTRY VALUES(165, 'OM', 'Omán',null,null,null,null);
INSERT INTO COUNTRY VALUES(166, 'NL', 'Países Bajos',null,null,null,null);
INSERT INTO COUNTRY VALUES(167, 'PK', 'Pakistán',null,null,null,null);
INSERT INTO COUNTRY VALUES(168, 'PW', 'Palau',null,null,null,null);
INSERT INTO COUNTRY VALUES(169, 'PS', 'Palestina',null,null,null,null);
INSERT INTO COUNTRY VALUES(170, 'PA', 'Panamá',null,null,null,null);
INSERT INTO COUNTRY VALUES(171, 'PG', 'Papúa Nueva Guinea',null,null,null,null);
INSERT INTO COUNTRY VALUES(172, 'PY', 'Paraguay',null,null,null,null);
INSERT INTO COUNTRY VALUES(173, 'PE', 'Perú',null,null,null,null);
INSERT INTO COUNTRY VALUES(174, 'PN', 'Islas Pitcairn',null,null,null,null);
INSERT INTO COUNTRY VALUES(175, 'PF', 'Polinesia Francesa',null,null,null,null);
INSERT INTO COUNTRY VALUES(176, 'PL', 'Polonia',null,null,null,null);
INSERT INTO COUNTRY VALUES(177, 'PT', 'Portugal',null,null,null,null);
INSERT INTO COUNTRY VALUES(178, 'PR', 'Puerto Rico',null,null,null,null);
INSERT INTO COUNTRY VALUES(179, 'QA', 'Qatar',null,null,null,null);
INSERT INTO COUNTRY VALUES(180, 'GB', 'Reino Unido',null,null,null,null);
INSERT INTO COUNTRY VALUES(181, 'RE', 'Reunión',null,null,null,null);
INSERT INTO COUNTRY VALUES(182, 'RW', 'Ruanda',null,null,null,null);
INSERT INTO COUNTRY VALUES(183, 'RO', 'Rumania',null,null,null,null);
INSERT INTO COUNTRY VALUES(184, 'RU', 'Rusia',null,null,null,null);
INSERT INTO COUNTRY VALUES(185, 'EH', 'Sahara Occidental',null,null,null,null);
INSERT INTO COUNTRY VALUES(186, 'SB', 'Islas Salomón',null,null,null,null);
INSERT INTO COUNTRY VALUES(187, 'WS', 'Samoa',null,null,null,null);
INSERT INTO COUNTRY VALUES(188, 'AS', 'Samoa Americana',null,null,null,null);
INSERT INTO COUNTRY VALUES(189, 'KN', 'San Cristóbal y Nevis',null,null,null,null);
INSERT INTO COUNTRY VALUES(190, 'SM', 'San Marino',null,null,null,null);
INSERT INTO COUNTRY VALUES(191, 'PM', 'San Pedro y Miquelón',null,null,null,null);
INSERT INTO COUNTRY VALUES(192, 'VC', 'San Vicente y las Granadinas',null,null,null,null);
INSERT INTO COUNTRY VALUES(193, 'SH', 'Santa Helena',null,null,null,null);
INSERT INTO COUNTRY VALUES(194, 'LC', 'Santa Lucía',null,null,null,null);
INSERT INTO COUNTRY VALUES(195, 'ST', 'Santo Tomé y Príncipe',null,null,null,null);
INSERT INTO COUNTRY VALUES(196, 'SN', 'Senegal',null,null,null,null);
INSERT INTO COUNTRY VALUES(197, 'CS', 'Serbia y Montenegro',null,null,null,null);
INSERT INTO COUNTRY VALUES(198, 'SC', 'Seychelles',null,null,null,null);
INSERT INTO COUNTRY VALUES(199, 'SL', 'Sierra Leona',null,null,null,null);
INSERT INTO COUNTRY VALUES(200, 'SG', 'Singapur',null,null,null,null);
INSERT INTO COUNTRY VALUES(201, 'SY', 'Siria',null,null,null,null);
INSERT INTO COUNTRY VALUES(202, 'SO', 'Somalia',null,null,null,null);
INSERT INTO COUNTRY VALUES(203, 'LK', 'Sri Lanka',null,null,null,null);
INSERT INTO COUNTRY VALUES(204, 'SZ', 'Suazilandia',null,null,null,null);
INSERT INTO COUNTRY VALUES(205, 'ZA', 'Sudáfrica',null,null,null,null);
INSERT INTO COUNTRY VALUES(206, 'SD', 'Sudán',null,null,null,null);
INSERT INTO COUNTRY VALUES(207, 'SE', 'Suecia',null,null,null,null);
INSERT INTO COUNTRY VALUES(208, 'CH', 'Suiza',null,null,null,null);
INSERT INTO COUNTRY VALUES(209, 'SR', 'Surinam',null,null,null,null);
INSERT INTO COUNTRY VALUES(210, 'SJ', 'Svalbard y Jan Mayen',null,null,null,null);
INSERT INTO COUNTRY VALUES(211, 'TH', 'Tailandia',null,null,null,null);
INSERT INTO COUNTRY VALUES(212, 'TW', 'Taiwán',null,null,null,null);
INSERT INTO COUNTRY VALUES(213, 'TZ', 'Tanzania',null,null,null,null);
INSERT INTO COUNTRY VALUES(214, 'TJ', 'Tayikistán',null,null,null,null);
INSERT INTO COUNTRY VALUES(215, 'IO', 'Territorio Británico del Océano Índico',null,null,null,null);
INSERT INTO COUNTRY VALUES(216, 'TF', 'Territorios Australes Franceses',null,null,null,null);
INSERT INTO COUNTRY VALUES(217, 'TL', 'Timor Oriental',null,null,null,null);
INSERT INTO COUNTRY VALUES(218, 'TG', 'Togo',null,null,null,null);
INSERT INTO COUNTRY VALUES(219, 'TK', 'Tokelau',null,null,null,null);
INSERT INTO COUNTRY VALUES(220, 'TO', 'Tonga',null,null,null,null);
INSERT INTO COUNTRY VALUES(221, 'TT', 'Trinidad y Tobago',null,null,null,null);
INSERT INTO COUNTRY VALUES(222, 'TN', 'Túnez',null,null,null,null);
INSERT INTO COUNTRY VALUES(223, 'TC', 'Islas Turcas y Caicos',null,null,null,null);
INSERT INTO COUNTRY VALUES(224, 'TM', 'Turkmenistán',null,null,null,null);
INSERT INTO COUNTRY VALUES(225, 'TR', 'Turquía',null,null,null,null);
INSERT INTO COUNTRY VALUES(226, 'TV', 'Tuvalu',null,null,null,null);
INSERT INTO COUNTRY VALUES(227, 'UA', 'Ucrania',null,null,null,null);
INSERT INTO COUNTRY VALUES(228, 'UG', 'Uganda',null,null,null,null);
INSERT INTO COUNTRY VALUES(229, 'UY', 'Uruguay',null,null,null,null);
INSERT INTO COUNTRY VALUES(230, 'UZ', 'Uzbekistán',null,null,null,null);
INSERT INTO COUNTRY VALUES(231, 'VU', 'Vanuatu',null,null,null,null);
INSERT INTO COUNTRY VALUES(232, 'VE', 'Venezuela',null,null,null,null);
INSERT INTO COUNTRY VALUES(233, 'VN', 'Vietnam',null,null,null,null);
INSERT INTO COUNTRY VALUES(234, 'VG', 'Islas Vírgenes Británicas',null,null,null,null);
INSERT INTO COUNTRY VALUES(235, 'VI', 'Islas Vírgenes de los Estados Unidos',null,null,null,null);
INSERT INTO COUNTRY VALUES(236, 'WF', 'Wallis y Futuna',null,null,null,null);
INSERT INTO COUNTRY VALUES(237, 'YE', 'Yemen',null,null,null,null);
INSERT INTO COUNTRY VALUES(238, 'DJ', 'Yibuti',null,null,null,null);
INSERT INTO COUNTRY VALUES(239, 'ZM', 'Zambia',null,null,null,null);
INSERT INTO COUNTRY VALUES(240, 'ZW', 'Zimbabue',null,null,null,null);
