info:
  description: Sample Spring Boot MyBatis Application
  version: 
---

####################
# PROFILE unittest #
####################
spring:
  profiles: default
datasources:
  chinook:
    jdbcUrl: jdbc:mysql://localhost:3306/Chinook
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    poolName: AtlasHikariCP
    maxLifetime: 1200000
    maximumPoolSize: 10
    minimumIdle: 1
