metrics:
 datadog:
 # Required
 enabled: true # This flag enables or disables the datadog reporter
 transport: http # http | udp 
 period: 1 # Time, in seconds, between every call to Datadog API. The lower this value the more information will be send to Datadog
 # HTTP Transport
 apiKey: 0518892d8b29adb03ad8616c806f90a0 # Datadog API key used to authenticate every request to Datadog API
 connectTimeout: 5000 # Optional
 socketTimeout:  5000 # Optional
 # UDP Transport
 statsdHost: # Optional | localhost
 statsdPort: # Optional | 8125  
 statsdPrefix: # Optional | empty 
 # Optional
 host: crequena-hbeds # Logical name associated to all the events send by this application
 tags: # Optional | empty 
 ec2Host: false
 prefix: # Optional | empty 