package com.sample.db.mapper;


import com.sample.db.pojos.Album;
import com.sample.db.pojos.AlbumExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface AlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Album
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int countByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Album
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int deleteByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Album
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Delete({
        "delete from Album",
        "where AlbumId = #{albumid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer albumid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Album
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Insert({
        "insert into Album (AlbumId, Title, ",
        "ArtistId)",
        "values (#{albumid,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{artistid,jdbcType=INTEGER})"
    })
    int insert(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Album
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int insertSelective(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Album
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    List<Album> selectByExample(AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Album
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Select({
        "select",
        "AlbumId, Title, ArtistId",
        "from Album",
        "where AlbumId = #{albumid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Album selectByPrimaryKey(Integer albumid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Album
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int updateByExampleSelective(@Param("record") Album record, @Param("example") AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Album
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int updateByExample(@Param("record") Album record, @Param("example") AlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Album
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int updateByPrimaryKeySelective(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Album
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Update({
        "update Album",
        "set Title = #{title,jdbcType=VARCHAR},",
          "ArtistId = #{artistid,jdbcType=INTEGER}",
        "where AlbumId = #{albumid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Album record);
}
