package com.sample.db.mapper;


import com.sample.db.pojos.Artist;
import com.sample.db.pojos.ArtistExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface ArtistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Artist
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int countByExample(ArtistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Artist
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int deleteByExample(ArtistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Artist
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Delete({
        "delete from Artist",
        "where ArtistId = #{artistid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer artistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Artist
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Insert({
        "insert into Artist (ArtistId, Name)",
        "values (#{artistid,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR})"
    })
    int insert(Artist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Artist
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int insertSelective(Artist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Artist
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    List<Artist> selectByExample(ArtistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Artist
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Select({
        "select",
        "ArtistId, Name",
        "from Artist",
        "where ArtistId = #{artistid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Artist selectByPrimaryKey(Integer artistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Artist
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int updateByExampleSelective(@Param("record") Artist record, @Param("example") ArtistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Artist
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int updateByExample(@Param("record") Artist record, @Param("example") ArtistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Artist
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int updateByPrimaryKeySelective(Artist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Artist
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Update({
        "update Artist",
        "set Name = #{name,jdbcType=VARCHAR}",
        "where ArtistId = #{artistid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Artist record);
}
