package com.sample.db.mapper;


import com.sample.db.pojos.Invoice;
import com.sample.db.pojos.InvoiceExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface InvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Invoice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int countByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Invoice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int deleteByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Invoice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Delete({
        "delete from Invoice",
        "where InvoiceId = #{invoiceid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer invoiceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Invoice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Insert({
        "insert into Invoice (InvoiceId, CustomerId, ",
        "InvoiceDate, BillingAddress, ",
        "BillingCity, BillingState, ",
        "BillingCountry, BillingPostalCode, ",
        "Total)",
        "values (#{invoiceid,jdbcType=INTEGER}, #{customerid,jdbcType=INTEGER}, ",
        "#{invoicedate,jdbcType=TIMESTAMP}, #{billingaddress,jdbcType=VARCHAR}, ",
        "#{billingcity,jdbcType=VARCHAR}, #{billingstate,jdbcType=VARCHAR}, ",
        "#{billingcountry,jdbcType=VARCHAR}, #{billingpostalcode,jdbcType=VARCHAR}, ",
        "#{total,jdbcType=DECIMAL})"
    })
    int insert(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Invoice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int insertSelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Invoice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    List<Invoice> selectByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Invoice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Select({
        "select",
        "InvoiceId, CustomerId, InvoiceDate, BillingAddress, BillingCity, BillingState, ",
        "BillingCountry, BillingPostalCode, Total",
        "from Invoice",
        "where InvoiceId = #{invoiceid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Invoice selectByPrimaryKey(Integer invoiceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Invoice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int updateByExampleSelective(@Param("record") Invoice record, @Param("example") InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Invoice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int updateByExample(@Param("record") Invoice record, @Param("example") InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Invoice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int updateByPrimaryKeySelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Invoice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Update({
        "update Invoice",
        "set CustomerId = #{customerid,jdbcType=INTEGER},",
          "InvoiceDate = #{invoicedate,jdbcType=TIMESTAMP},",
          "BillingAddress = #{billingaddress,jdbcType=VARCHAR},",
          "BillingCity = #{billingcity,jdbcType=VARCHAR},",
          "BillingState = #{billingstate,jdbcType=VARCHAR},",
          "BillingCountry = #{billingcountry,jdbcType=VARCHAR},",
          "BillingPostalCode = #{billingpostalcode,jdbcType=VARCHAR},",
          "Total = #{total,jdbcType=DECIMAL}",
        "where InvoiceId = #{invoiceid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Invoice record);
}
