package com.sample.db.mapper;


import com.sample.db.pojos.MediaType;
import com.sample.db.pojos.MediaTypeExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface MediaTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MediaType
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int countByExample(MediaTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MediaType
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int deleteByExample(MediaTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MediaType
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Delete({
        "delete from MediaType",
        "where MediaTypeId = #{mediatypeid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer mediatypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MediaType
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Insert({
        "insert into MediaType (MediaTypeId, Name)",
        "values (#{mediatypeid,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR})"
    })
    int insert(MediaType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MediaType
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int insertSelective(MediaType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MediaType
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    List<MediaType> selectByExample(MediaTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MediaType
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Select({
        "select",
        "MediaTypeId, Name",
        "from MediaType",
        "where MediaTypeId = #{mediatypeid,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    MediaType selectByPrimaryKey(Integer mediatypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MediaType
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int updateByExampleSelective(@Param("record") MediaType record, @Param("example") MediaTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MediaType
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int updateByExample(@Param("record") MediaType record, @Param("example") MediaTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MediaType
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    int updateByPrimaryKeySelective(MediaType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MediaType
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    @Update({
        "update MediaType",
        "set Name = #{name,jdbcType=VARCHAR}",
        "where MediaTypeId = #{mediatypeid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MediaType record);
}
