info:
 description: Sample Application
 version: 
endpoints:
 restart:
  enabled: true
 shutdown:
  enabled: true
 health:
  enabled: true
  sensitive: false


####################
# PROFILE DEV     #
####################
---
spring:
 profiles: test
 datasource:
  driverClassName: org.h2.Driver
  jdbcUrl: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: 
  maximumPoolSize: 5

