package com.sample.db.pojos;

public class Artist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Artist.ArtistId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer artistid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Artist.Name
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Artist.ArtistId
     *
     * @return the value of Artist.ArtistId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getArtistid() {
        return artistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Artist.ArtistId
     *
     * @param artistid the value for Artist.ArtistId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setArtistid(Integer artistid) {
        this.artistid = artistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Artist.Name
     *
     * @return the value of Artist.Name
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Artist.Name
     *
     * @param name the value for Artist.Name
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}
