package com.sample.db.pojos;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.CustomerId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.FirstName
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.LastName
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String lastname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Company
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Address
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.City
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.State
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Country
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.PostalCode
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String postalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Phone
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Fax
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Email
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.SupportRepId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer supportrepid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.CustomerId
     *
     * @return the value of Customer.CustomerId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.CustomerId
     *
     * @param customerid the value for Customer.CustomerId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.FirstName
     *
     * @return the value of Customer.FirstName
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.FirstName
     *
     * @param firstname the value for Customer.FirstName
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.LastName
     *
     * @return the value of Customer.LastName
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.LastName
     *
     * @param lastname the value for Customer.LastName
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Company
     *
     * @return the value of Customer.Company
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Company
     *
     * @param company the value for Customer.Company
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Address
     *
     * @return the value of Customer.Address
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Address
     *
     * @param address the value for Customer.Address
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.City
     *
     * @return the value of Customer.City
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.City
     *
     * @param city the value for Customer.City
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.State
     *
     * @return the value of Customer.State
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.State
     *
     * @param state the value for Customer.State
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Country
     *
     * @return the value of Customer.Country
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Country
     *
     * @param country the value for Customer.Country
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.PostalCode
     *
     * @return the value of Customer.PostalCode
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.PostalCode
     *
     * @param postalcode the value for Customer.PostalCode
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Phone
     *
     * @return the value of Customer.Phone
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Phone
     *
     * @param phone the value for Customer.Phone
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Fax
     *
     * @return the value of Customer.Fax
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Fax
     *
     * @param fax the value for Customer.Fax
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Email
     *
     * @return the value of Customer.Email
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Email
     *
     * @param email the value for Customer.Email
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.SupportRepId
     *
     * @return the value of Customer.SupportRepId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getSupportrepid() {
        return supportrepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.SupportRepId
     *
     * @param supportrepid the value for Customer.SupportRepId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setSupportrepid(Integer supportrepid) {
        this.supportrepid = supportrepid;
    }
}
