package com.sample.db.pojos;

import java.util.Date;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.EmployeeId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer employeeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.LastName
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String lastname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.FirstName
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Title
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.ReportsTo
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer reportsto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.BirthDate
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Date birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.HireDate
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Date hiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Address
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.City
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.State
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Country
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.PostalCode
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String postalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Phone
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Fax
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.Email
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.EmployeeId
     *
     * @return the value of Employee.EmployeeId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.EmployeeId
     *
     * @param employeeid the value for Employee.EmployeeId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.LastName
     *
     * @return the value of Employee.LastName
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.LastName
     *
     * @param lastname the value for Employee.LastName
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.FirstName
     *
     * @return the value of Employee.FirstName
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.FirstName
     *
     * @param firstname the value for Employee.FirstName
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.Title
     *
     * @return the value of Employee.Title
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.Title
     *
     * @param title the value for Employee.Title
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.ReportsTo
     *
     * @return the value of Employee.ReportsTo
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getReportsto() {
        return reportsto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.ReportsTo
     *
     * @param reportsto the value for Employee.ReportsTo
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setReportsto(Integer reportsto) {
        this.reportsto = reportsto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.BirthDate
     *
     * @return the value of Employee.BirthDate
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.BirthDate
     *
     * @param birthdate the value for Employee.BirthDate
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.HireDate
     *
     * @return the value of Employee.HireDate
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.HireDate
     *
     * @param hiredate the value for Employee.HireDate
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.Address
     *
     * @return the value of Employee.Address
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.Address
     *
     * @param address the value for Employee.Address
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.City
     *
     * @return the value of Employee.City
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.City
     *
     * @param city the value for Employee.City
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.State
     *
     * @return the value of Employee.State
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.State
     *
     * @param state the value for Employee.State
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.Country
     *
     * @return the value of Employee.Country
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.Country
     *
     * @param country the value for Employee.Country
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.PostalCode
     *
     * @return the value of Employee.PostalCode
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.PostalCode
     *
     * @param postalcode the value for Employee.PostalCode
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.Phone
     *
     * @return the value of Employee.Phone
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.Phone
     *
     * @param phone the value for Employee.Phone
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.Fax
     *
     * @return the value of Employee.Fax
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.Fax
     *
     * @param fax the value for Employee.Fax
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.Email
     *
     * @return the value of Employee.Email
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.Email
     *
     * @param email the value for Employee.Email
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}
