package com.sample.db.pojos;

import java.math.BigDecimal;
import java.util.Date;

public class Invoice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Invoice.InvoiceId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer invoiceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Invoice.CustomerId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Invoice.InvoiceDate
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Date invoicedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Invoice.BillingAddress
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String billingaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Invoice.BillingCity
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String billingcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Invoice.BillingState
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String billingstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Invoice.BillingCountry
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String billingcountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Invoice.BillingPostalCode
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String billingpostalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Invoice.Total
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private BigDecimal total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Invoice.InvoiceId
     *
     * @return the value of Invoice.InvoiceId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getInvoiceid() {
        return invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Invoice.InvoiceId
     *
     * @param invoiceid the value for Invoice.InvoiceId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setInvoiceid(Integer invoiceid) {
        this.invoiceid = invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Invoice.CustomerId
     *
     * @return the value of Invoice.CustomerId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Invoice.CustomerId
     *
     * @param customerid the value for Invoice.CustomerId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Invoice.InvoiceDate
     *
     * @return the value of Invoice.InvoiceDate
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Date getInvoicedate() {
        return invoicedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Invoice.InvoiceDate
     *
     * @param invoicedate the value for Invoice.InvoiceDate
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setInvoicedate(Date invoicedate) {
        this.invoicedate = invoicedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Invoice.BillingAddress
     *
     * @return the value of Invoice.BillingAddress
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getBillingaddress() {
        return billingaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Invoice.BillingAddress
     *
     * @param billingaddress the value for Invoice.BillingAddress
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setBillingaddress(String billingaddress) {
        this.billingaddress = billingaddress == null ? null : billingaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Invoice.BillingCity
     *
     * @return the value of Invoice.BillingCity
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getBillingcity() {
        return billingcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Invoice.BillingCity
     *
     * @param billingcity the value for Invoice.BillingCity
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setBillingcity(String billingcity) {
        this.billingcity = billingcity == null ? null : billingcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Invoice.BillingState
     *
     * @return the value of Invoice.BillingState
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getBillingstate() {
        return billingstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Invoice.BillingState
     *
     * @param billingstate the value for Invoice.BillingState
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setBillingstate(String billingstate) {
        this.billingstate = billingstate == null ? null : billingstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Invoice.BillingCountry
     *
     * @return the value of Invoice.BillingCountry
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getBillingcountry() {
        return billingcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Invoice.BillingCountry
     *
     * @param billingcountry the value for Invoice.BillingCountry
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setBillingcountry(String billingcountry) {
        this.billingcountry = billingcountry == null ? null : billingcountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Invoice.BillingPostalCode
     *
     * @return the value of Invoice.BillingPostalCode
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getBillingpostalcode() {
        return billingpostalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Invoice.BillingPostalCode
     *
     * @param billingpostalcode the value for Invoice.BillingPostalCode
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setBillingpostalcode(String billingpostalcode) {
        this.billingpostalcode = billingpostalcode == null ? null : billingpostalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Invoice.Total
     *
     * @return the value of Invoice.Total
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Invoice.Total
     *
     * @param total the value for Invoice.Total
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
}
