package com.sample.db.pojos;

public class MediaType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MediaType.MediaTypeId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer mediatypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MediaType.Name
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MediaType.MediaTypeId
     *
     * @return the value of MediaType.MediaTypeId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getMediatypeid() {
        return mediatypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MediaType.MediaTypeId
     *
     * @param mediatypeid the value for MediaType.MediaTypeId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setMediatypeid(Integer mediatypeid) {
        this.mediatypeid = mediatypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MediaType.Name
     *
     * @return the value of MediaType.Name
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MediaType.Name
     *
     * @param name the value for MediaType.Name
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}
