package com.sample.db.pojos;

import java.math.BigDecimal;

public class Track {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Track.TrackId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer trackid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Track.Name
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Track.AlbumId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer albumid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Track.MediaTypeId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer mediatypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Track.GenreId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer genreid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Track.Composer
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private String composer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Track.Milliseconds
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer milliseconds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Track.Bytes
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private Integer bytes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Track.UnitPrice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    private BigDecimal unitprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Track.TrackId
     *
     * @return the value of Track.TrackId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getTrackid() {
        return trackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Track.TrackId
     *
     * @param trackid the value for Track.TrackId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setTrackid(Integer trackid) {
        this.trackid = trackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Track.Name
     *
     * @return the value of Track.Name
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Track.Name
     *
     * @param name the value for Track.Name
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Track.AlbumId
     *
     * @return the value of Track.AlbumId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getAlbumid() {
        return albumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Track.AlbumId
     *
     * @param albumid the value for Track.AlbumId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setAlbumid(Integer albumid) {
        this.albumid = albumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Track.MediaTypeId
     *
     * @return the value of Track.MediaTypeId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getMediatypeid() {
        return mediatypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Track.MediaTypeId
     *
     * @param mediatypeid the value for Track.MediaTypeId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setMediatypeid(Integer mediatypeid) {
        this.mediatypeid = mediatypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Track.GenreId
     *
     * @return the value of Track.GenreId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getGenreid() {
        return genreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Track.GenreId
     *
     * @param genreid the value for Track.GenreId
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setGenreid(Integer genreid) {
        this.genreid = genreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Track.Composer
     *
     * @return the value of Track.Composer
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public String getComposer() {
        return composer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Track.Composer
     *
     * @param composer the value for Track.Composer
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setComposer(String composer) {
        this.composer = composer == null ? null : composer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Track.Milliseconds
     *
     * @return the value of Track.Milliseconds
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getMilliseconds() {
        return milliseconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Track.Milliseconds
     *
     * @param milliseconds the value for Track.Milliseconds
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setMilliseconds(Integer milliseconds) {
        this.milliseconds = milliseconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Track.Bytes
     *
     * @return the value of Track.Bytes
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public Integer getBytes() {
        return bytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Track.Bytes
     *
     * @param bytes the value for Track.Bytes
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setBytes(Integer bytes) {
        this.bytes = bytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Track.UnitPrice
     *
     * @return the value of Track.UnitPrice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public BigDecimal getUnitprice() {
        return unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Track.UnitPrice
     *
     * @param unitprice the value for Track.UnitPrice
     *
     * @mbggenerated Thu Jun 05 12:50:06 CEST 2014
     */
    public void setUnitprice(BigDecimal unitprice) {
        this.unitprice = unitprice;
    }
}
